### ISSUE TITLE
Laravel 5.5 support

### ISSUE THREAD

**Issue by rogervila** [signifly/laravel-pivot-events#1]
Hello,

Could it be possible to [downgrade the minimum laravel version to 5.5](https://github.com/signifly/laravel-pivot-events/blob/master/composer.json#L20)?

Thank you very much.

**Comment by pactode** [comment]
Hi @rogervila,

Sure, I made a new release to support this.

**Comment by rogervila** [comment]
Amazing! 
Thank you very much :)
